name: Gradle Package

on:
  push:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout project source code
        uses: actions/checkout@v4
      - name: Setup java version 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: Log java version
        run: java --version
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: List files
        run: ls -ltr
      - name: Run build with Gradle Wrapper
        run: ./gradlew build